Repository WoltLab/WCF, pull requests merged in 2019-04, with the labels that each got.

#2887 Add missing support for JS loaded content in WCF.InlineEditor
  wcfsetup/install/files/js/WCF.js
Labels: Bug

#2702 support app installation via cli
  wcfsetup/install/files/lib/system/cli/command/PackageCLICommand.class.php
Labels: Enhancement

#2821 Use API_VERSION for update servers and xsd paths
  com.woltlab.wcf/aclOption.xml
  com.woltlab.wcf/acpMenu.xml
  com.woltlab.wcf/acpSearchProvider.xml
  com.woltlab.wcf/bbcode.xml
  com.woltlab.wcf/box.xml
  com.woltlab.wcf/clipboardAction.xml
  com.woltlab.wcf/coreObject.xml
  com.woltlab.wcf/cronjob.xml
  com.woltlab.wcf/eventListener.xml
  com.woltlab.wcf/mediaProvider.xml
  com.woltlab.wcf/menu.xml
  com.woltlab.wcf/menuItem.xml
  com.woltlab.wcf/objectType.xml
  com.woltlab.wcf/objectTypeDefinition.xml
  com.woltlab.wcf/option.xml
  com.woltlab.wcf/package.xml
  com.woltlab.wcf/packageInstallationPlugin.xml
  com.woltlab.wcf/page.xml
  com.woltlab.wcf/smiley.xml
  com.woltlab.wcf/templateListener.xml
  com.woltlab.wcf/userGroupOption.xml
  com.woltlab.wcf/userMenu.xml
  com.woltlab.wcf/userNotificationEvent.xml
  com.woltlab.wcf/userOption.xml
  com.woltlab.wcf/userProfileMenu.xml
  wcfsetup/install/files/lib/data/language/LanguageEditor.class.php
  wcfsetup/install/files/lib/data/style/StyleEditor.class.php
  wcfsetup/install/files/lib/system/devtools/package/DevtoolsPackageXmlWriter.class.php
  wcfsetup/install/files/lib/system/devtools/pip/TXmlGuiPackageInstallationPlugin.class.php
  wcfsetup/install/files/lib/system/package/plugin/LanguagePackageInstallationPlugin.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
  wcfsetup/setup/db/install.sql
  wcfsetup/setup/lang/setup_de.xml
  wcfsetup/setup/lang/setup_en.xml
Labels: Enhancement

#2895 Show exception file and line in exception dialog
  wcfsetup/install/files/js/WoltLabSuite/Core/Ajax/Request.js
  wcfsetup/install/files/lib/action/TAJAXException.class.php
  wcfsetup/install/files/lib/system/exception/AJAXException.class.php
Labels: Enhancement

#2890 New group type "Owner"
  wcfsetup/install/files/acp/style/layout.scss
  wcfsetup/install/files/acp/templates/footer.tpl
  wcfsetup/install/files/acp/templates/optionFieldList.tpl
  wcfsetup/install/files/acp/templates/userAdd.tpl
  wcfsetup/install/files/acp/templates/userGroupAdd.tpl
  wcfsetup/install/files/acp/templates/userGroupList.tpl
  wcfsetup/install/files/acp/templates/userGroupOption.tpl
  wcfsetup/install/files/acp/templates/userGroupPromoteOwner.tpl
  wcfsetup/install/files/lib/acp/form/UserEditForm.class.php
  wcfsetup/install/files/lib/acp/form/UserGroupAssignmentAddForm.class.php
  wcfsetup/install/files/lib/acp/form/UserGroupEditForm.class.php
  wcfsetup/install/files/lib/acp/form/UserGroupOptionForm.class.php
  wcfsetup/install/files/lib/acp/form/UserGroupPromoteOwnerForm.class.php
  wcfsetup/install/files/lib/data/user/User.class.php
  wcfsetup/install/files/lib/data/user/group/UserGroup.class.php
  wcfsetup/install/files/lib/data/user/group/UserGroupAction.class.php
  wcfsetup/install/files/lib/system/WCF.class.php
  wcfsetup/install/files/lib/system/WCFACP.class.php
  wcfsetup/install/files/lib/system/bulk/processing/user/AbstractUserBulkProcessingAction.class.php
  wcfsetup/install/files/lib/system/bulk/processing/user/AbstractUserGroupsUserBulkProcessingAction.class.php
  wcfsetup/install/files/lib/system/cache/builder/UserGroupPermissionCacheBuilder.class.php
  wcfsetup/install/files/lib/system/option/user/group/UserGroupOptionHandler.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
  wcfsetup/setup/db/install.sql
Labels: New Feature

#2770 Automatic client-side attachment scaling
  com.woltlab.wcf/option.xml
  com.woltlab.wcf/templates/messageFormAttachments.tpl
  constants.php
  wcfsetup/install/files/js/3rdParty/pica.js
  wcfsetup/install/files/js/WCF.Attachment.js
  wcfsetup/install/files/js/WCF.js
  wcfsetup/install/files/js/WoltLabSuite/Core/FileUtil.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Image/ExifUtil.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Image/ImageUtil.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Image/Resizer.js
  wcfsetup/install/files/js/require.config.js
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: New Feature

#2901 Redesign of the "Install Package" page
  wcfsetup/install/files/acp/js/WCF.ACP.js
  wcfsetup/install/files/acp/style/layout.scss
  wcfsetup/install/files/acp/templates/packageSearchResultList.tpl
  wcfsetup/install/files/acp/templates/packageStartInstall.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Package/PrepareInstallation.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Package/Search.js
  wcfsetup/install/files/lib/data/package/update/PackageUpdateAction.class.php
  wcfsetup/install/files/lib/data/package/update/ViewablePackageUpdate.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Enhancement

#2909 Show exception extra information on exception log view page
  wcfsetup/install/files/acp/templates/exceptionLogView.tpl
Labels: Enhancement
