Repository WoltLab/WCF, pull requests merged in 2020-05, with the labels that each got.

#3297 Add AnchorFunctionTemplatePlugin
  wcfsetup/install/files/lib/system/template/plugin/AnchorFunctionTemplatePlugin.class.php
Labels: Enhancement

#3298 Add DatabaseObjectList::getSingleObject()
  wcfsetup/install/files/lib/data/DatabaseObjectList.class.php
  wcfsetup/install/files/lib/data/article/ViewableArticle.class.php
  wcfsetup/install/files/lib/data/comment/ViewableComment.class.php
  wcfsetup/install/files/lib/data/comment/response/ViewableCommentResponse.class.php
  wcfsetup/install/files/lib/data/moderation/queue/ViewableModerationQueue.class.php
  wcfsetup/install/files/lib/system/package/plugin/StylePackageInstallationPlugin.class.php
Labels: Enhancement

#3317 Dynamic event listener with extra support for DBOActions
  wcfsetup/install/files/lib/system/event/listener/AbstractEventListener.class.php
Labels: Enhancement, ⬆️ High Priority

#3296 Mark required fields in output when using form builder
  com.woltlab.wcf/templates/__form.tpl
  com.woltlab.wcf/templates/__formContainer.tpl
  com.woltlab.wcf/templates/__formField.tpl
  wcfsetup/install/files/acp/templates/__form.tpl
  wcfsetup/install/files/acp/templates/__formContainer.tpl
  wcfsetup/install/files/acp/templates/__formField.tpl
  wcfsetup/install/files/lib/system/form/builder/FormDocument.class.php
  wcfsetup/install/files/lib/system/form/builder/IFormDocument.class.php
  wcfsetup/install/files/lib/system/form/builder/container/FormContainer.class.php
  wcfsetup/install/files/lib/system/form/builder/container/IFormContainer.class.php
  wcfsetup/install/files/lib/system/form/builder/container/wysiwyg/WysiwygFormContainer.class.php
  wcfsetup/install/files/style/layout/form.scss
Labels: Enhancement

#3299 Prevent infinite loop for nested language items
  wcfsetup/install/files/lib/data/language/Language.class.php
Labels: Enhancement

#3322 Add UserTemplatePlugin
  wcfsetup/install/files/lib/system/template/plugin/UserFunctionTemplatePlugin.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Enhancement

#3328 Remove links in user notifications messages
  wcfsetup/install/files/lib/data/trophy/Trophy.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Enhancement

#3338 Guard ENTERPRISE_MODE_DOMAIN_OVERRIDE functionality against PHP_SAPI !== 'cli'
  wcfsetup/install/files/lib/data/application/Application.class.php
Labels: Bug
