Repository WoltLab/WCF, pull requests merged in 2020-06, with the labels that each got.

#3314 Add proper management of missing language items
  com.woltlab.wcf/acpMenu.xml
  wcfsetup/install/files/acp/templates/__devtoolsMissingLanguageItemStackTrace.tpl
  wcfsetup/install/files/acp/templates/devtoolsMissingLanguageItemList.tpl
  wcfsetup/install/files/lib/acp/page/DevtoolsMissingLanguageItemListPage.class.php
  wcfsetup/install/files/lib/acp/page/IndexPage.class.php
  wcfsetup/install/files/lib/data/devtools/missing/language/item/DevtoolsMissingLanguageItem.class.php
  wcfsetup/install/files/lib/data/devtools/missing/language/item/DevtoolsMissingLanguageItemAction.class.php
  wcfsetup/install/files/lib/data/devtools/missing/language/item/DevtoolsMissingLanguageItemEditor.class.php
  wcfsetup/install/files/lib/data/devtools/missing/language/item/DevtoolsMissingLanguageItemList.class.php
  wcfsetup/install/files/lib/data/language/Language.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
  wcfsetup/setup/db/install.sql
Labels: New Feature

#3363 Add permission to restrict hiding online status
  com.woltlab.wcf/userGroupOption.xml
  com.woltlab.wcf/userOption.xml
  wcfsetup/install/files/lib/data/user/UserProfile.class.php
  wcfsetup/install/files/lib/data/user/online/UserOnline.class.php
  wcfsetup/install/files/lib/data/user/online/UsersOnlineList.class.php
  wcfsetup/install/files/lib/system/box/WhoWasOnlineBoxController.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Enhancement

#3375 New UI for the notification settings
  com.woltlab.wcf/templates/notificationSettings.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Controller/User/Notification/Settings.js
  wcfsetup/install/files/style/ui/notification.scss
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#3382 Fix updating decimal fields with default value
  wcfsetup/install/files/lib/system/database/table/column/AbstractDecimalDatabaseTableColumn.class.php
Labels: Bug

#3358 Indicate the existance of further trophies in special trophy list on …
  com.woltlab.wcf/templates/user.tpl
  wcfsetup/install/files/lib/data/user/UserProfile.class.php
  wcfsetup/install/files/lib/page/UserPage.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#3372 Improve layout for embedded videos in ugc
  com.woltlab.wcf/templates/__videoAttachmentBBCode.tpl
  wcfsetup/install/files/lib/system/bbcode/AttachmentBBCode.class.php
  wcfsetup/install/files/style/bbcode/media.scss
Labels: Feature

#3383 Add audio player for embedded audio attachments
  com.woltlab.wcf/templates/__audioAttachmentBBCode.tpl
  wcfsetup/install/files/lib/system/bbcode/AttachmentBBCode.class.php
Labels: Feature

#3385 Output external images with unknown dimensions in AMP pages
  com.woltlab.wcf/templates/ampHeader.tpl
  wcfsetup/install/files/lib/system/html/output/AmpHtmlOutputProcessor.class.php
Labels: Bug

#3374 Deduplicate Exceptions in ExceptionLogView
  wcfsetup/install/files/acp/style/layout.scss
  wcfsetup/install/files/acp/templates/exceptionLogView.tpl
  wcfsetup/install/files/lib/acp/page/ExceptionLogViewPage.class.php
  wcfsetup/install/files/lib/util/ExceptionLogUtil.class.php
Labels: Feature

#3409 Fix PHP 8 compatibility for WCF::handleError()
  wcfsetup/install/files/lib/system/WCF.class.php
Labels: Bug

#3396 Update composer dependencies
  wcfsetup/install/files/lib/system/api/autoload.php
  wcfsetup/install/files/lib/system/api/bin/pscss
  wcfsetup/install/files/lib/system/api/bin/pscss.bat
  wcfsetup/install/files/lib/system/api/chrisjean/php-ico/license.txt
  wcfsetup/install/files/lib/system/api/composer.lock
  wcfsetup/install/files/lib/system/api/composer/autoload_classmap.php
  wcfsetup/install/files/lib/system/api/composer/autoload_namespaces.php
  wcfsetup/install/files/lib/system/api/composer/autoload_real.php
  wcfsetup/install/files/lib/system/api/composer/autoload_static.php
  wcfsetup/install/files/lib/system/api/composer/installed.json
  wcfsetup/install/files/lib/system/api/erusev/parsedown/Parsedown.php
  wcfsetup/install/files/lib/system/api/pear/pear_exception/composer.json
  wcfsetup/install/files/lib/system/api/symfony/css-selector/LICENSE
  wcfsetup/install/files/lib/system/api/symfony/css-selector/Node/AbstractNode.php
  wcfsetup/install/files/lib/system/api/symfony/css-selector/Parser/Handler/StringHandler.php
  wcfsetup/install/files/lib/system/api/symfony/css-selector/XPath/Extension/FunctionExtension.php
  wcfsetup/install/files/lib/system/api/symfony/polyfill-mbstring/Mbstring.php
  wcfsetup/install/files/lib/system/api/symfony/polyfill-mbstring/README.md
  wcfsetup/install/files/lib/system/api/symfony/polyfill-mbstring/Resources/unidata/lowerCase.php
  wcfsetup/install/files/lib/system/api/symfony/polyfill-mbstring/Resources/unidata/upperCase.php
  wcfsetup/install/files/lib/system/api/symfony/polyfill-mbstring/bootstrap.php
  wcfsetup/install/files/lib/system/api/symfony/polyfill-mbstring/composer.json
Labels: Feature

#3323 Register activation method by user and admin
  com.woltlab.wcf/clipboardAction.xml
  com.woltlab.wcf/option.xml
  com.woltlab.wcf/templates/accountManagement.tpl
  com.woltlab.wcf/templates/email_registerNeedActivation.tpl
  com.woltlab.wcf/templates/registerActivation.tpl
  com.woltlab.wcf/templates/user.tpl
  com.woltlab.wcf/templates/userNotice.tpl
  wcfsetup/install/files/acp/templates/userList.tpl
  wcfsetup/install/files/acp/templates/userSearch.tpl
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.3_emailConfirmation.php
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Editor.js
  wcfsetup/install/files/lib/acp/action/UserQuickSearchAction.class.php
  wcfsetup/install/files/lib/acp/page/IndexPage.class.php
  wcfsetup/install/files/lib/data/user/User.class.php
  wcfsetup/install/files/lib/data/user/UserAction.class.php
  wcfsetup/install/files/lib/data/user/UserProfile.class.php
  wcfsetup/install/files/lib/data/user/UserProfileAction.class.php
  wcfsetup/install/files/lib/form/AccountManagementForm.class.php
  wcfsetup/install/files/lib/form/EmailActivationForm.class.php
  wcfsetup/install/files/lib/form/RegisterActivationForm.class.php
  wcfsetup/install/files/lib/form/RegisterForm.class.php
  wcfsetup/install/files/lib/form/RegisterNewActivationCodeForm.class.php
  wcfsetup/install/files/lib/page/PaidSubscriptionListPage.class.php
  wcfsetup/install/files/lib/system/clipboard/action/UserClipboardAction.class.php
  wcfsetup/install/files/lib/system/condition/UserStateCondition.class.php
  wcfsetup/install/files/lib/system/cronjob/DailyMailNotificationCronjob.class.php
  wcfsetup/install/files/lib/system/importer/UserImporter.class.php
  wcfsetup/install/files/lib/system/user/notification/UserNotificationHandler.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
  wcfsetup/setup/db/install.sql
Labels: Feature
