Repository WoltLab/WCF, pull requests merged in 2020-08, with the labels that each got.

#3472 User rank live preview
  wcfsetup/install/files/acp/templates/labelAdd.tpl
  wcfsetup/install/files/acp/templates/userRankAdd.tpl
  wcfsetup/install/files/js/WCF.Label.js
Labels: Feature

#3145 Add all environment to event listener
  XSD/types.xsd
  wcfsetup/install/files/lib/data/event/listener/EventListener.class.php
  wcfsetup/install/files/lib/system/cache/builder/EventListenerCacheBuilder.class.php
Labels: Feature

#3471 Disable visit tracking for search engines
  wcfsetup/install/files/lib/system/visitTracker/VisitTracker.class.php
Labels: Feature

#3466 Fixes exception when not using primary PayPal email
  wcfsetup/install/files/lib/action/PaypalCallbackAction.class.php
Labels: Bug, P1: Medium

#3449 Better password security estimation
  com.woltlab.wcf/option.xml
  com.woltlab.wcf/templates/accountManagement.tpl
  com.woltlab.wcf/templates/newPassword.tpl
  com.woltlab.wcf/templates/passwordStrengthLanguage.tpl
  com.woltlab.wcf/templates/register.tpl
  constants.php
  syncTemplates.json
  wcfsetup/install/files/acp/templates/passwordStrengthLanguage.tpl
  wcfsetup/install/files/acp/templates/userAdd.tpl
  wcfsetup/install/files/js/3rdParty/zxcvbn.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/User/PasswordStrength.js
  wcfsetup/install/files/js/require.config.js
  wcfsetup/install/files/lib/data/user/UserRegistrationAction.class.php
  wcfsetup/install/files/lib/form/AccountManagementForm.class.php
  wcfsetup/install/files/lib/form/NewPasswordForm.class.php
  wcfsetup/install/files/lib/form/RegisterForm.class.php
  wcfsetup/install/files/lib/system/WCF.class.php
  wcfsetup/install/files/lib/util/UserRegistrationUtil.class.php
  wcfsetup/install/files/style/layout/form.scss
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#3505 Clear thumbnail handles as soon as possible
  wcfsetup/install/files/lib/acp/form/StyleAddForm.class.php
  wcfsetup/install/files/lib/data/style/StyleAction.class.php
  wcfsetup/install/files/lib/system/upload/DefaultUploadFileSaveStrategy.class.php
  wcfsetup/install/files/lib/system/worker/UserRebuildDataWorker.class.php
  wcfsetup/install/files/lib/util/ImageUtil.class.php
Labels: Bug

#3483 Overhauled the page action buttons' behavior
  wcfsetup/install/files/js/WoltLabSuite/Core/Bootstrap.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Dom/Util.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Page/Action.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Page/JumpToTop.js
  wcfsetup/install/files/js/wcf.globalHelper.js
  wcfsetup/install/files/style/ui/pageAction.scss
Labels: Feature

#3500 Add missing phrases to English 3rd party register language items
  wcfsetup/install/lang/en.xml
Labels: Bug

#3513 Added possiblity to disable the preview-button
  wcfsetup/install/files/lib/system/form/builder/container/wysiwyg/WysiwygFormContainer.class.php
Labels: Feature, P2: Low

#3519 Overflow handling for reaction popovers on smartphones
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Reaction/Handler.js
  wcfsetup/install/files/style/ui/reactions.scss
Labels: Feature

#3523 Fix the scrollbar for dropdowns on large tablets
  wcfsetup/install/files/js/WCF.js
Labels: Bug

#3525 Prevent rich metacode being dysfunctional in new messages
  com.woltlab.wcf/templates/codeMetaCode.tpl
  com.woltlab.wcf/templates/quoteMetaCode.tpl
  com.woltlab.wcf/templates/spoilerMetaCode.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Bbcode/Spoiler.js
Labels: Bug, P1: Medium

#3524 Clean up package update server management
  com.woltlab.wcf/package.xml
  wcfsetup/install/files/acp/templates/packageUpdateServerAdd.tpl
  wcfsetup/install/files/acp/templates/packageUpdateServerList.tpl
  wcfsetup/install/files/acp/templates/packageUpdateUnauthorized.tpl
  wcfsetup/install/files/lib/acp/form/PackageUpdateServerAddForm.class.php
  wcfsetup/install/files/lib/acp/form/PackageUpdateServerEditForm.class.php
  wcfsetup/install/files/lib/acp/page/PackageUpdateServerListPage.class.php
  wcfsetup/install/files/lib/core.functions.php
  wcfsetup/install/files/lib/data/package/update/server/PackageUpdateServer.class.php
  wcfsetup/install/files/lib/data/package/update/server/PackageUpdateServerAction.class.php
  wcfsetup/install/files/lib/system/io/HttpFactory.class.php
  wcfsetup/install/files/lib/system/style/StyleCompiler.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature
