Repository WoltLab/WCF, pull requests merged in 2020-12, with the labels that each got.

#3785 Convert the ACP article modules to TypeScript
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Article/Add.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Article/InlineEditor.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Article/Add.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Article/Add.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Article/InlineEditor.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Article/InlineEditor.ts
Labels: Feature

#3783 Add form field for active user's password
  com.woltlab.wcf/templates/__userPasswordFormField.tpl
  syncTemplates.json
  wcfsetup/install/files/acp/templates/__userPasswordFormField.tpl
  wcfsetup/install/files/lib/system/form/builder/field/user/UserPasswordField.class.php
Labels: Feature

#3786 Optimize LikeRebuildDataWorker performance
  wcfsetup/install/files/lib/system/worker/LikeRebuildDataWorker.class.php
Labels: Bug

#3793 Validate package installation permissions in StyleImportForm
  wcfsetup/install/files/lib/acp/form/PackageStartInstallForm.class.php
  wcfsetup/install/files/lib/acp/form/StyleImportForm.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Bug

#3764 Make marking required fields optional with form builder
  com.woltlab.wcf/templates/__formField.tpl
  wcfsetup/install/files/acp/templates/__formField.tpl
  wcfsetup/install/files/lib/system/form/builder/FormDocument.class.php
  wcfsetup/install/files/lib/system/form/builder/IFormDocument.class.php
Labels: Feature

#3765 Support renaming database table columns via PHP API
  wcfsetup/install/files/lib/system/database/editor/MySQLDatabaseEditor.class.php
  wcfsetup/install/files/lib/system/database/table/DatabaseTableChangeProcessor.class.php
  wcfsetup/install/files/lib/system/database/table/column/AbstractDatabaseTableColumn.class.php
  wcfsetup/install/files/lib/system/database/table/column/IDatabaseTableColumn.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#3781 Remove reCAPTCHA v1 implementation
  com.woltlab.wcf/templates/recaptcha.tpl
  wcfsetup/install/files/acp/templates/recaptcha.tpl
  wcfsetup/install/files/lib/form/RecaptchaForm.class.php
  wcfsetup/install/files/lib/system/captcha/RecaptchaHandler.class.php
  wcfsetup/install/files/lib/system/recaptcha/RecaptchaHandler.class.php
  wcfsetup/install/files/lib/system/recaptcha/RecaptchaHandlerV2.class.php
Labels: Bug

#3778 Use consistent phrasing
  wcfsetup/install/lang/de.xml
Labels: Bug

#3799 Validate primary indices with null columns in PHP DB API
  wcfsetup/install/files/lib/system/database/table/DatabaseTableChangeProcessor.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Bug

#3807 Greatly improve the performance of GIF processing with ImageMagick
  wcfsetup/install/files/lib/system/image/adapter/ImagickImageAdapter.class.php
Labels: Feature

#3810 Prevent the unintentional removal of values for groups that are not being edited
  wcfsetup/install/files/lib/data/user/group/option/UserGroupOptionAction.class.php
Labels: Bug, P1: Medium

#3806 Add `LanguageItemFormNode`
  com.woltlab.wcf/templates/__multifactorDisableExplanation.tpl
  com.woltlab.wcf/templates/__multifactorManageInitialBackup.tpl
  com.woltlab.wcf/templates/multifactorManageEmail.tpl
  wcfsetup/install/files/lib/form/MultifactorDisableForm.class.php
  wcfsetup/install/files/lib/form/MultifactorManageForm.class.php
  wcfsetup/install/files/lib/system/form/builder/LanguageItemFormNode.class.php
  wcfsetup/install/files/lib/system/user/multifactor/BackupMultifactorMethod.class.php
  wcfsetup/install/files/lib/system/user/multifactor/EmailMultifactorMethod.class.php
Labels: Feature

#3787 Convert ACP UI user modules to TypeScript
  wcfsetup/install/files/acp/templates/rebuildData.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Content/Remove/Handler.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Editor.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Worker.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Dialog.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/User/Content/Remove/Handler.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/User/Content/Remove/Handler.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/User/Editor.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/User/Editor.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Worker.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Worker.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Dialog.ts
Labels: Feature

#3788 Convert `Acp/Ui/Style/Editor` to TypeScript
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Style/Editor.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Dom/Util.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Style/Editor.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Style/Editor.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Dom/Util.ts
Labels: Feature

#3789 Convert `Acp/Ui/Template/Group/Copy` to TypeScript
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Template/Group/Copy.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Template/Group/Copy.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Template/Group/Copy.ts
Labels: Feature

#3790 Convert ACP UI trophy modules to TypeScript
  wcfsetup/install/files/acp/templates/trophyAdd.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Trophy/Badge.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Trophy/Upload.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Trophy/Badge.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Trophy/Badge.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Trophy/Upload.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Trophy/Upload.ts
Labels: Feature

#3818 Fix style previews pointing to the style's asset folder
  com.woltlab.wcf/package.xml
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.3.1_style.php
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.3.2_style.php
Labels: Bug

#3822 Support adding CSS classes to actual form field in form builder
  com.woltlab.wcf/templates/__booleanFormField.tpl
  com.woltlab.wcf/templates/__buttonFormField.tpl
  com.woltlab.wcf/templates/__checkboxFormField.tpl
  com.woltlab.wcf/templates/__dateFormField.tpl
  com.woltlab.wcf/templates/__emailFormField.tpl
  com.woltlab.wcf/templates/__itemListFormField.tpl
  com.woltlab.wcf/templates/__multifactorBackupCodeField.tpl
  com.woltlab.wcf/templates/__multifactorEmailCodeField.tpl
  com.woltlab.wcf/templates/__multifactorTotpCodeField.tpl
  com.woltlab.wcf/templates/__multilineTextFormField.tpl
  com.woltlab.wcf/templates/__multipleSelectionFormField.tpl
  com.woltlab.wcf/templates/__numericFormField.tpl
  com.woltlab.wcf/templates/__radioButtonFormField.tpl
  com.woltlab.wcf/templates/__singleSelectionFormField.tpl
  com.woltlab.wcf/templates/__textFormField.tpl
  wcfsetup/install/files/acp/templates/__booleanFormField.tpl
  wcfsetup/install/files/acp/templates/__buttonFormField.tpl
  wcfsetup/install/files/acp/templates/__checkboxFormField.tpl
  wcfsetup/install/files/acp/templates/__dateFormField.tpl
  wcfsetup/install/files/acp/templates/__emailFormField.tpl
  wcfsetup/install/files/acp/templates/__itemListFormField.tpl
  wcfsetup/install/files/acp/templates/__multifactorBackupCodeField.tpl
  wcfsetup/install/files/acp/templates/__multifactorEmailCodeField.tpl
  wcfsetup/install/files/acp/templates/__multifactorTotpCodeField.tpl
  wcfsetup/install/files/acp/templates/__multilineTextFormField.tpl
  wcfsetup/install/files/acp/templates/__multipleSelectionFormField.tpl
  wcfsetup/install/files/acp/templates/__numericFormField.tpl
  wcfsetup/install/files/acp/templates/__radioButtonFormField.tpl
  wcfsetup/install/files/acp/templates/__singleSelectionFormField.tpl
  wcfsetup/install/files/acp/templates/__textFormField.tpl
  wcfsetup/install/files/lib/system/form/builder/field/AbstractNumericFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/BooleanFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/ButtonFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/CheckboxFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/DateFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/EmailFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/ICssClassFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/ItemListFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/MultipleSelectionFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/RadioButtonFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/SingleSelectionFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/TCssClassFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/TextFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/backup/CodeFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/email/CodeFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/totp/CodeFormField.class.php
Labels: Feature

#3688 Use runtime cache instead of `UserProfile::getUserProfile()`
  wcfsetup/install/files/lib/form/ModerationReportForm.class.php
Labels: Feature

#3819 Add autocomplete support for form builder fields
  com.woltlab.wcf/templates/__emailFormField.tpl
  com.woltlab.wcf/templates/__multifactorBackupCodeField.tpl
  com.woltlab.wcf/templates/__multifactorEmailCodeField.tpl
  com.woltlab.wcf/templates/__multifactorTotpCodeField.tpl
  com.woltlab.wcf/templates/__multilineTextFormField.tpl
  com.woltlab.wcf/templates/__numericFormField.tpl
  com.woltlab.wcf/templates/__textFormField.tpl
  com.woltlab.wcf/templates/__userPasswordFormField.tpl
  com.woltlab.wcf/templates/__usernameFormField.tpl
  wcfsetup/install/files/acp/templates/__emailFormField.tpl
  wcfsetup/install/files/acp/templates/__multifactorBackupCodeField.tpl
  wcfsetup/install/files/acp/templates/__multifactorEmailCodeField.tpl
  wcfsetup/install/files/acp/templates/__multifactorTotpCodeField.tpl
  wcfsetup/install/files/acp/templates/__multilineTextFormField.tpl
  wcfsetup/install/files/acp/templates/__numericFormField.tpl
  wcfsetup/install/files/acp/templates/__textFormField.tpl
  wcfsetup/install/files/acp/templates/__userPasswordFormField.tpl
  wcfsetup/install/files/acp/templates/__usernameFormField.tpl
  wcfsetup/install/files/lib/system/form/builder/field/AbstractNumericFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/EmailFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/FloatFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/IAutoCompleteFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/IntegerFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/MultilineTextFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/TAutoCompleteFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/TTextAutoCompleteFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/TextFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/UrlFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/user/UserPasswordField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/user/UsernameFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/backup/CodeFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/email/CodeFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/totp/CodeFormField.class.php
Labels: Feature

#3825 Add support for the inputmode attribute in form builder
  com.woltlab.wcf/templates/__emailFormField.tpl
  com.woltlab.wcf/templates/__multifactorBackupCodeField.tpl
  com.woltlab.wcf/templates/__multifactorEmailCodeField.tpl
  com.woltlab.wcf/templates/__multifactorTotpCodeField.tpl
  com.woltlab.wcf/templates/__multilineTextFormField.tpl
  com.woltlab.wcf/templates/__numericFormField.tpl
  com.woltlab.wcf/templates/__textFormField.tpl
  wcfsetup/install/files/acp/templates/__emailFormField.tpl
  wcfsetup/install/files/acp/templates/__multifactorBackupCodeField.tpl
  wcfsetup/install/files/acp/templates/__multifactorEmailCodeField.tpl
  wcfsetup/install/files/acp/templates/__multifactorTotpCodeField.tpl
  wcfsetup/install/files/acp/templates/__multilineTextFormField.tpl
  wcfsetup/install/files/acp/templates/__numericFormField.tpl
  wcfsetup/install/files/acp/templates/__textFormField.tpl
  wcfsetup/install/files/lib/system/form/builder/field/AbstractNumericFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/EmailFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/IInputModeFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/TInputModeFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/TextFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/UrlFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/backup/CodeFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/email/CodeFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/totp/CodeFormField.class.php
Labels: Feature

#3832 Validate column names in indices when using PHP DB API
  wcfsetup/install/files/lib/system/database/table/DatabaseTableChangeProcessor.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Bug

#3833 Add support for pattern attribute in form builder
  com.woltlab.wcf/templates/__emailFormField.tpl
  com.woltlab.wcf/templates/__multifactorBackupCodeField.tpl
  com.woltlab.wcf/templates/__multifactorEmailCodeField.tpl
  com.woltlab.wcf/templates/__multifactorTotpCodeField.tpl
  com.woltlab.wcf/templates/__multilineTextFormField.tpl
  com.woltlab.wcf/templates/__textFormField.tpl
  wcfsetup/install/files/acp/templates/__emailFormField.tpl
  wcfsetup/install/files/acp/templates/__multifactorBackupCodeField.tpl
  wcfsetup/install/files/acp/templates/__multifactorEmailCodeField.tpl
  wcfsetup/install/files/acp/templates/__multifactorTotpCodeField.tpl
  wcfsetup/install/files/acp/templates/__multilineTextFormField.tpl
  wcfsetup/install/files/acp/templates/__textFormField.tpl
  wcfsetup/install/files/lib/system/form/builder/field/EmailFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/IPatternFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/TPatternFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/TextFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/backup/CodeFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/email/CodeFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/totp/CodeFormField.class.php
Labels: Feature

#3826 Refactor search query parse of MysqlSearchEngine
  wcfsetup/install/files/lib/system/search/mysql/MysqlSearchEngine.class.php
Labels: Bug

#3838 Support adding attributes to actual form field in form builder
  com.woltlab.wcf/templates/__booleanFormField.tpl
  com.woltlab.wcf/templates/__buttonFormField.tpl
  com.woltlab.wcf/templates/__checkboxFormField.tpl
  com.woltlab.wcf/templates/__dateFormField.tpl
  com.woltlab.wcf/templates/__emailFormField.tpl
  com.woltlab.wcf/templates/__itemListFormField.tpl
  com.woltlab.wcf/templates/__multifactorBackupCodeField.tpl
  com.woltlab.wcf/templates/__multifactorEmailCodeField.tpl
  com.woltlab.wcf/templates/__multifactorTotpCodeField.tpl
  com.woltlab.wcf/templates/__multilineTextFormField.tpl
  com.woltlab.wcf/templates/__multipleSelectionFormField.tpl
  com.woltlab.wcf/templates/__numericFormField.tpl
  com.woltlab.wcf/templates/__radioButtonFormField.tpl
  com.woltlab.wcf/templates/__tagFormField.tpl
  com.woltlab.wcf/templates/__textFormField.tpl
  com.woltlab.wcf/templates/__userPasswordFormField.tpl
  com.woltlab.wcf/templates/__usernameFormField.tpl
  com.woltlab.wcf/templates/__wysiwygFormField.tpl
  syncTemplates.json
  wcfsetup/install/files/acp/templates/__booleanFormField.tpl
  wcfsetup/install/files/acp/templates/__buttonFormField.tpl
  wcfsetup/install/files/acp/templates/__checkboxFormField.tpl
  wcfsetup/install/files/acp/templates/__dateFormField.tpl
  wcfsetup/install/files/acp/templates/__emailFormField.tpl
  wcfsetup/install/files/acp/templates/__itemListFormField.tpl
  wcfsetup/install/files/acp/templates/__multifactorBackupCodeField.tpl
  wcfsetup/install/files/acp/templates/__multifactorEmailCodeField.tpl
  wcfsetup/install/files/acp/templates/__multifactorTotpCodeField.tpl
  wcfsetup/install/files/acp/templates/__multilineTextFormField.tpl
  wcfsetup/install/files/acp/templates/__multipleSelectionFormField.tpl
  wcfsetup/install/files/acp/templates/__numericFormField.tpl
  wcfsetup/install/files/acp/templates/__radioButtonFormField.tpl
  wcfsetup/install/files/acp/templates/__tagFormField.tpl
  wcfsetup/install/files/acp/templates/__textFormField.tpl
  wcfsetup/install/files/acp/templates/__userPasswordFormField.tpl
  wcfsetup/install/files/acp/templates/__usernameFormField.tpl
  wcfsetup/install/files/acp/templates/__wysiwygFormField.tpl
  wcfsetup/install/files/lib/system/form/builder/field/AbstractNumericFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/BooleanFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/ButtonFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/DateFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/EmailFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/IAttributeFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/ItemListFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/MultilineTextFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/MultipleSelectionFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/RadioButtonFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/TAttributeFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/TInputAttributeFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/TextFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/tag/TagFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/user/UserPasswordField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/user/UsernameFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/wysiwyg/WysiwygFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/backup/CodeFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/email/CodeFormField.class.php
  wcfsetup/install/files/lib/system/user/multifactor/totp/CodeFormField.class.php
Labels: Feature

#3824 Preserve package server credentials during the upgrade from 5.2 to 5.3.
  com.woltlab.wcf/package.xml
  com.woltlab.wcf/update_5.3.sql
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.3_packageServer.php
Labels: Bug
