Repository WoltLab/WCF, pull requests merged in 2020-11, with the labels that each got.

#3672 Add and use InvalidObjectArgument
  wcfsetup/install/files/lib/system/condition/AbstractObjectTextPropertyCondition.class.php
  wcfsetup/install/files/lib/system/condition/AbstractTimestampCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserAvatarCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserCoverPhotoCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserEmailCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserIntegerPropertyCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserLanguageCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserOptionsCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserRegistrationDateCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserRegistrationDateIntervalCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserSignatureCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserStateCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserTrophyCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserUserIDCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserUsernameCondition.class.php
  wcfsetup/install/files/lib/system/condition/article/ArticleCategoryCondition.class.php
  wcfsetup/install/files/lib/system/condition/user/UserLastActivityTimeIntervalDaysCondition.class.php
  wcfsetup/install/files/lib/system/condition/user/activity/event/UserActivityEventExcludedObjectTypeCondition.class.php
  wcfsetup/install/files/lib/system/condition/user/trophy/UserTrophyExcludedTrophiesCondition.class.php
  wcfsetup/install/files/lib/system/condition/user/trophy/UserTrophyExcludedTrophyCategoriesCondition.class.php
  wcfsetup/install/files/lib/system/exception/InvalidObjectArgument.class.php
Labels: Feature

#3682 Menu item add
  wcfsetup/install/files/acp/templates/menuItemAdd.tpl
  wcfsetup/install/files/acp/templates/menuList.tpl
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#3683 Add permissions for attachments in signatures
  com.woltlab.wcf/userGroupOption.xml
  wcfsetup/install/files/lib/system/attachment/SignatureAttachmentObjectType.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#3684 Support rebuilding activity points on user rank list page
  wcfsetup/install/files/acp/templates/userRankList.tpl
Labels: Feature

#3690 Convert `Ui/Poll/Editor` to TypeScript
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Poll/Editor.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Poll/Editor.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Poll/Editor.ts
Labels: Feature

#3695 Convert modules for Redactor to TypeScript
  global.d.ts
  package-lock.json
  package.json
  wcfsetup/install/files/js/3rdParty/prism/build.js
  wcfsetup/install/files/js/3rdParty/prism/prism-meta.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Bootstrap.js
  wcfsetup/install/files/js/WoltLabSuite/Core/StringUtil.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Article.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Autosave.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Code.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/DragAndDrop.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Editor.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Format.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Html.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Link.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Mention.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Metacode.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Page.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/PseudoHeader.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Quote.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Spoiler.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/Table.js
  wcfsetup/install/files/js/WoltLabSuite/Core/prism-meta.js
  wcfsetup/install/files/lib/system/bbcode/BBCodeHandler.class.php
  wcfsetup/install/files/ts/WoltLabSuite/Core/Bootstrap.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/StringUtil.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Article.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Article.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Autosave.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Autosave.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Code.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Code.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/DragAndDrop.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/DragAndDrop.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Editor.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Format.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Format.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Html.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Html.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Link.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Link.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Mention.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Mention.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Metacode.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Metacode.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Page.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Page.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/PseudoHeader.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/PseudoHeader.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Quote.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Quote.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Spoiler.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Spoiler.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Table.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Table.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/TabMenu/Simple.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/prism-meta.ts
Labels: Feature

#3696 Convert message modules to TypeScript
  global.d.ts
  package-lock.json
  package.json
  wcfsetup/install/files/js/WoltLabSuite/Core/Controller/Captcha.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Message/InlineEditor.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Message/Manager.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Message/Reply.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Message/Share.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Message/TwitterEmbed.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Message/UserConsent.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Captcha.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Captcha.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/InlineEditor.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/InlineEditor.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/Manager.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/Manager.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/Reply.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/Reply.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/Share.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/Share.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/TwitterEmbed.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/TwitterEmbed.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/UserConsent.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/UserConsent.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Editor.ts
Labels: Feature

#3700 Convert the comment (response) modules to TypeScript
  global.d.ts
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Comment/Add.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Comment/Edit.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Comment/Response/Add.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Comment/Response/Edit.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Notification.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Comment/Add.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Comment/Add.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Comment/Edit.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Comment/Edit.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Comment/Response/Add.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Comment/Response/Add.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Comment/Response/Edit.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Comment/Response/Edit.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Notification.ts
Labels: Feature

#3694 Add button form field
  com.woltlab.wcf/templates/__buttonFormField.tpl
  com.woltlab.wcf/templates/__isNotClickedFormFieldDependency.tpl
  syncTemplates.json
  wcfsetup/install/files/acp/templates/__buttonFormField.tpl
  wcfsetup/install/files/acp/templates/__isNotClickedFormFieldDependency.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Form/Builder/Dialog.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Form/Builder/Field/Button.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Form/Builder/Field/Dependency/IsNotClicked.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Dialog.js
  wcfsetup/install/files/lib/system/form/builder/field/ButtonFormField.class.php
  wcfsetup/install/files/lib/system/form/builder/field/dependency/IsNotClickedFormFieldDependency.class.php
  wcfsetup/install/files/ts/WoltLabSuite/Core/Form/Builder/Dialog.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Form/Builder/Field/Button.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Form/Builder/Field/Dependency/IsNotClicked.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Dialog.ts
Labels: Feature

#3710 Remove obsolete code for update from 2.1 to 3.0
  wcfsetup/install/files/lib/system/cache/builder/EventListenerCacheBuilder.class.php
Labels: Feature

#3706 Remove enquire.js
  wcfsetup/install/files/js/3rdParty/enquire.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Bootstrap.js
  wcfsetup/install/files/js/require.config.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Bootstrap.js
Labels: Feature

#3705 Convert `Ui/File/Upload` to TypeScript
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/File/Upload.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Upload.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Upload/Data.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/File/Upload.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/File/Upload.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/User/CoverPhoto/Upload.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Upload.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Upload/Data.ts
Labels: Feature

#3709 Convert i18n modules to TypeScript
  global.d.ts
  wcfsetup/install/files/js/WoltLabSuite/Core/Language/Chooser.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Language/Input.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Language/Text.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Language/Chooser.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Language/Chooser.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Language/Input.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Language/Input.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Language/Text.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Language/Text.ts
Labels: Feature

#3685 Use `jslang` in more places
  com.woltlab.wcf/templates/__singleMediaSelectionFormField.tpl
  com.woltlab.wcf/templates/__wysiwygCmsToolbar.tpl
  com.woltlab.wcf/templates/articleAdd.tpl
  com.woltlab.wcf/templates/birthdaySearchableOptionType.tpl
  com.woltlab.wcf/templates/pageHeaderUser.tpl
  com.woltlab.wcf/templates/register.tpl
  com.woltlab.wcf/templates/settings.tpl
  com.woltlab.wcf/templates/wysiwygToolbar.tpl
  wcfsetup/install/files/acp/templates/__singleMediaSelectionFormField.tpl
  wcfsetup/install/files/acp/templates/__wysiwygCmsToolbar.tpl
  wcfsetup/install/files/acp/templates/articleAdd.tpl
  wcfsetup/install/files/acp/templates/birthdaySearchableOptionType.tpl
  wcfsetup/install/files/acp/templates/boxAdd.tpl
  wcfsetup/install/files/acp/templates/cacheList.tpl
  wcfsetup/install/files/acp/templates/captchaQuestionList.tpl
  wcfsetup/install/files/acp/templates/dataImport.tpl
  wcfsetup/install/files/acp/templates/devtoolsMissingLanguageItemList.tpl
  wcfsetup/install/files/acp/templates/devtoolsProjectList.tpl
  wcfsetup/install/files/acp/templates/labelAdd.tpl
  wcfsetup/install/files/acp/templates/labelGroupList.tpl
  wcfsetup/install/files/acp/templates/labelList.tpl
  wcfsetup/install/files/acp/templates/pageHeaderUser.tpl
  wcfsetup/install/files/acp/templates/rebuildData.tpl
  wcfsetup/install/files/acp/templates/sendMailUserBulkProcessing.tpl
  wcfsetup/install/files/acp/templates/sitemapList.tpl
  wcfsetup/install/files/acp/templates/tagList.tpl
  wcfsetup/install/files/acp/templates/templateGroupList.tpl
  wcfsetup/install/files/acp/templates/templateList.tpl
  wcfsetup/install/files/acp/templates/userActivityPointOption.tpl
  wcfsetup/install/files/acp/templates/userAdd.tpl
  wcfsetup/install/files/acp/templates/userGroupAssignmentList.tpl
  wcfsetup/install/files/acp/templates/userRankAdd.tpl
  wcfsetup/install/files/acp/templates/wysiwygToolbar.tpl
Labels: Bug

#3708 Add labeledUrl user option type
  wcfsetup/install/files/acp/templates/userOptionAdd.tpl
  wcfsetup/install/files/lib/acp/form/UserOptionAddForm.class.php
  wcfsetup/install/files/lib/acp/form/UserOptionEditForm.class.php
  wcfsetup/install/files/lib/data/user/option/UserOption.class.php
  wcfsetup/install/files/lib/system/option/LabeledUrlOptionType.class.php
  wcfsetup/install/files/lib/system/option/user/LabeledUrlUserOptionOutput.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
  wcfsetup/setup/db/install.sql
Labels: Feature

#3724 Verify the existence of the old imagePath in update_com.woltlab.wcf_5.3_style.php
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.3_style.php
Labels: Bug

#3726 Place the `@charset` at the very beginning of the generated CSS
  wcfsetup/install/files/lib/system/style/StyleCompiler.class.php
Labels: Bug, P1: Medium

#3727 Fix typo in favicon template filename
  com.woltlab.wcf/package.xml
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.3.1_faviconTemplate.php
  wcfsetup/install/files/lib/acp/form/StyleEditForm.class.php
  wcfsetup/install/files/lib/data/style/StyleAction.class.php
Labels: Bug

#3739 Fix style preview images when upgrading from 5.2
  com.woltlab.wcf/package.xml
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.3.1_faviconTemplate.php
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.3.1_style.php
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.3_style.php
Labels: Bug

#3740 Clean up comments when removing moderation queues
  com.woltlab.wcf/package.xml
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.2.10_orphanedComments.php
  wcfsetup/install/files/lib/system/cronjob/ModerationQueueCronjob.class.php
Labels: Bug

#3750 Update pelago/emogrifier to 5.0
  wcfsetup/install/files/lib/system/api/composer.json
  wcfsetup/install/files/lib/system/api/composer.lock
  wcfsetup/install/files/lib/system/api/composer/InstalledVersions.php
  wcfsetup/install/files/lib/system/api/composer/installed.json
  wcfsetup/install/files/lib/system/api/composer/installed.php
  wcfsetup/install/files/lib/system/api/pelago/emogrifier/CHANGELOG.md
  wcfsetup/install/files/lib/system/api/pelago/emogrifier/README.md
  wcfsetup/install/files/lib/system/api/pelago/emogrifier/composer.json
  wcfsetup/install/files/lib/system/api/pelago/emogrifier/phpunit.xml
  wcfsetup/install/files/lib/system/api/pelago/emogrifier/src/CssInliner.php
  wcfsetup/install/files/lib/system/api/pelago/emogrifier/src/HtmlProcessor/AbstractHtmlProcessor.php
  wcfsetup/install/files/lib/system/api/pelago/emogrifier/src/HtmlProcessor/CssToAttributeConverter.php
  wcfsetup/install/files/lib/system/api/pelago/emogrifier/src/HtmlProcessor/HtmlPruner.php
  wcfsetup/install/files/lib/system/api/pelago/emogrifier/src/Utilities/CssConcatenator.php
Labels: Feature

#3763 HTTP request timeouts
  wcfsetup/install/files/lib/action/ImageProxyAction.class.php
  wcfsetup/install/files/lib/system/style/FontManager.class.php
  wcfsetup/install/files/lib/util/HTTPRequest.class.php
Labels: Bug

#3761 Converted remaining UI modules to TypeScript
  global.d.ts
  wcfsetup/install/files/js/WoltLabSuite/Core/Bootstrap.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Notification/Handler.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Color/Picker.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/DragAndDrop.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Mobile.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Redactor/DragAndDrop.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Bootstrap.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Notification/Handler.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Notification/Handler.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Color/Picker.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Color/Picker.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/DragAndDrop.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/DragAndDrop.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Mobile.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Mobile.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/DragAndDrop.ts
Labels: Feature

#3770 Convert `Acp/Ui/Menu/Item/Handler` to TypeScript
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Menu/Item/Handler.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Menu/Item/Handler.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Menu/Item/Handler.ts
Labels: Feature

#3773 Convert the ACP page modules to TypeScript
  global.d.ts
  package-lock.json
  package.json
  wcfsetup/install/files/acp/templates/pageBoxOrder.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Page/Add.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Page/BoxOrder.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Page/Copy.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Page/Menu.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Page/Add.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Page/Add.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Page/BoxOrder.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Page/BoxOrder.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Page/Copy.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Page/Copy.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Page/Menu.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Page/Menu.ts
Labels: Feature

#3772 Convert the ACP package modules to TypeScript
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Package/PrepareInstallation.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Package/Search.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Package/PrepareInstallation.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Package/PrepareInstallation.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Package/Search.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Package/Search.ts
Labels: Feature

#3771 Convert the ACP option modules to TypeScript
  wcfsetup/install/files/acp/templates/__optionRewriteTest.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Option/EmailSmtpTest.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Option/RewriteGenerator.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Option/RewriteTest.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Option/EmailSmtpTest.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Option/EmailSmtpTest.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Option/RewriteGenerator.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Option/RewriteGenerator.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Option/RewriteTest.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Option/RewriteTest.ts
Labels: Feature

#3769 Convert ACP box modules to TypeScript
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Box/Add.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Box/Controller/Handler.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Box/Copy.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Box/Handler.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Box/Add.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Box/Add.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Box/Controller/Handler.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Box/Controller/Handler.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Box/Copy.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Box/Copy.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Box/Handler.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Box/Handler.ts
Labels: Feature

#3768 Convert the clipboard handler to TypeScript
  wcfsetup/install/files/js/WoltLabSuite/Core/Controller/Clipboard.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Clipboard.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Clipboard.ts
Labels: Feature
