Repository WoltLab/WCF, pull requests merged in 2020-10, with the labels that each got.

#3585 Improved the wording of the cronjob error message
  wcfsetup/install/files/lib/system/cronjob/CronjobScheduler.class.php
Labels: Feature

#3589 Check for the "jpeg" and "png" support of GD
  wcfsetup/install/files/acp/templates/systemCheck.tpl
  wcfsetup/install/files/lib/acp/page/SystemCheckPage.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#3596 Fix HEAD requests with `accept-encoding` header set
  wcfsetup/install/files/lib/system/api/composer.lock
  wcfsetup/install/files/lib/system/api/composer/installed.json
  wcfsetup/install/files/lib/system/api/guzzlehttp/guzzle/src/Handler/CurlFactory.php
Labels: Bug

#3598 Fix deprecation warnings in form builder in PHP 8
  wcfsetup/install/files/lib/system/form/builder/data/processor/CustomFormDataProcessor.class.php
  wcfsetup/install/files/lib/system/form/builder/field/validation/FormFieldValidator.class.php
Labels: Feature, P1: Medium

#3600 Support alphanumeric error code in ExceptionLogUtil::parseException()
  wcfsetup/install/files/lib/util/ExceptionLogUtil.class.php
Labels: Bug

#3602 Update defaultStyle after migrating styles
  com.woltlab.wcf/package.xml
Labels: Bug

#3615 Fix endless loop in removeExifData when the APP1 signature does not match
  wcfsetup/install/files/js/WoltLabSuite/Core/Image/ExifUtil.js
Labels: Bug

#3625 Remove the explicit passing of a Guzzle sink
  wcfsetup/install/files/lib/system/style/FontManager.class.php
  wcfsetup/install/files/lib/util/HTTPRequest.class.php
Labels: Feature

#3631 Clean up response headers
  wcfsetup/install/files/lib/util/HeaderUtil.class.php
Labels: Feature

#3630 Remove DatabaseTableUtil
  wcfsetup/install/files/lib/system/database/table/DatabaseTableUtil.class.php
Labels: Bug

#3626 Remove PHP 7.0 compatibility code for Reflection
  wcfsetup/install/files/lib/system/form/builder/data/processor/CustomFormDataProcessor.class.php
  wcfsetup/install/files/lib/system/form/builder/field/validation/FormFieldValidator.class.php
Labels: Feature

#3612 Backport CsrfTokenFunctionTemplatePlugin
  wcfsetup/install/files/lib/system/template/plugin/CsrfTokenFunctionTemplatePlugin.class.php
Labels: Feature

#3633 Add flood control API
  com.woltlab.wcf/objectTypeDefinition.xml
  wcfsetup/install/files/lib/system/cronjob/DailyCleanUpCronjob.class.php
  wcfsetup/install/files/lib/system/flood/FloodControl.class.php
  wcfsetup/setup/db/install.sql
Labels: Feature

#3646 Clean up user storage update logic
  wcfsetup/install/files/lib/system/user/storage/UserStorageHandler.class.php
Labels: Feature

#3637 Remove meta keywords
  com.woltlab.wcf/option.xml
  constants.php
  wcfsetup/install/files/acp/templates/pageAdd.tpl
  wcfsetup/install/files/acp/update_5.4_db.php
  wcfsetup/install/files/lib/acp/form/PageAddForm.class.php
  wcfsetup/install/files/lib/acp/form/PageEditForm.class.php
  wcfsetup/install/files/lib/data/language/LanguageEditor.class.php
  wcfsetup/install/files/lib/data/page/PageAction.class.php
  wcfsetup/install/files/lib/data/page/content/PageContent.class.php
  wcfsetup/install/files/lib/page/CmsPage.class.php
  wcfsetup/install/files/lib/system/MetaTagHandler.class.php
  wcfsetup/install/files/lib/system/WCF.class.php
  wcfsetup/install/files/lib/system/importer/PageImporter.class.php
  wcfsetup/install/files/lib/system/package/plugin/PagePackageInstallationPlugin.class.php
  wcfsetup/install/files/lib/system/user/notification/event/TTestablePageUserNotificationEvent.class.php
  wcfsetup/install/files/lib/system/version/PageVersionTrackerProvider.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
  wcfsetup/setup/db/install.sql
Labels: Feature

#3643 Add script to remove files during update to 5.4
  com.woltlab.wcf/package.xml
  wcfsetup/install/files/acp/update_5.4_removeFiles.php
Labels: Feature

#3654 Use new flood control API for comments
  com.woltlab.wcf/objectType.xml
  wcfsetup/install/files/lib/data/comment/CommentAction.class.php
  wcfsetup/install/files/lib/system/comment/CommentHandler.class.php
Labels: Feature

#3662 Skip system requirements during setup if they are met
  wcfsetup/install/files/lib/system/WCFSetup.class.php
Labels: Feature
