Repository WoltLab/WCF, pull requests merged in 2021-07, with the labels that each got.

#4355 Support wildcard for category name in `AclFormField`
  wcfsetup/install/files/lib/system/form/builder/field/acl/AclFormField.class.php
Labels: Feature

#4353 Modernize color picker and add `ColorFormField`
  com.woltlab.wcf/templates/__colorFormField.tpl
  ts/WoltLabSuite/Core/ColorUtil.ts
  ts/WoltLabSuite/Core/Ui/Color/Picker.ts
  wcfsetup/install/files/acp/templates/__colorFormField.tpl
  wcfsetup/install/files/acp/templates/styleAdd.tpl
  wcfsetup/install/files/acp/templates/trophyAdd.tpl
  wcfsetup/install/files/js/WCF.ColorPicker.js
  wcfsetup/install/files/js/WoltLabSuite/Core/ColorUtil.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Color/Picker.js
  wcfsetup/install/files/lib/system/form/builder/field/ColorFormField.class.php
  wcfsetup/install/files/style/ui/colorPicker.scss
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#4367 Make renaming columns with PHP DB API idempotent
  wcfsetup/install/files/lib/system/database/table/DatabaseTableChangeProcessor.class.php
Labels: Bug

#4368 Add check for GD support to PackageEnableUpgradeOverrideForm
  wcfsetup/install/files/lib/acp/form/PackageEnableUpgradeOverrideForm.class.php
Labels: Bug

#4372 Support sorting users in `UserOnlineListBoxController`
  wcfsetup/install/files/lib/system/box/UserOnlineListBoxController.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#4370 Remove support for the API compatibility tags from dev tools
  wcfsetup/install/files/lib/acp/form/DevtoolsProjectAddForm.class.php
  wcfsetup/install/files/lib/acp/form/DevtoolsProjectEditForm.class.php
  wcfsetup/install/files/lib/system/devtools/package/DevtoolsPackageXmlWriter.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Bug

#4375 Remove old workaround for the upgrade from 2.1 to 3.0
  wcfsetup/install/files/lib/system/request/ControllerMap.class.php
Labels: Bug

#4376 Remove the need to rebuild the active application
  wcfsetup/install/files/lib/system/application/AbstractApplication.class.php
  wcfsetup/install/files/lib/system/application/ApplicationHandler.class.php
  wcfsetup/install/files/lib/system/request/RequestHandler.class.php
Labels: Bug

#4381 Remove gzopen64() workaround
  wcfsetup/install.php
  wcfsetup/install/files/lib/system/io/GZipFile.class.php
Labels: Bug

#4371 Do not store API compatibility information within the database
  wcfsetup/install/files/acp/templates/package.tpl
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.5_clearPackageCompatibility.php
  wcfsetup/install/files/lib/acp/page/PackagePage.class.php
  wcfsetup/install/files/lib/system/package/PackageInstallationDispatcher.class.php
  wcfsetup/setup/db/install.sql
Labels: Bug

#4385 Do not store package compatibility from update servers within the database
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.5_clearPackageCompatibility.php
  wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php
  wcfsetup/setup/db/install.sql
Labels: Bug

#4392 Rename TOTP code form field to `onetimecode`
  wcfsetup/install/files/lib/system/user/multifactor/TotpMultifactorMethod.class.php
  wcfsetup/install/files/lib/system/user/multifactor/totp/CodeFormField.class.php
Labels: Bug, Feature

#4397 Improve Favicon handling in StyleAction
  wcfsetup/install/files/lib/data/style/StyleAction.class.php
Labels: Bug

#4399 Remove PROFILE_MAIL_USE_CAPTCHA
  com.woltlab.wcf/option.xml
  constants.php
  wcfsetup/install/files/lib/system/WCF.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Bug

#4383 Fix recursively loading embedded objects in articles
  wcfsetup/install/files/lib/data/article/ViewableArticleList.class.php
  wcfsetup/install/files/lib/data/article/content/ViewableArticleContentList.class.php
  wcfsetup/install/files/lib/system/message/embedded/object/ArticleMessageEmbeddedObjectHandler.class.php
Labels: Bug

#4401 Use `data:` URIs to load assets in WCFSetup
  wcfsetup/install.php
  wcfsetup/install/files/lib/system/WCFSetup.class.php
  wcfsetup/setup/template/header.tpl
  wcfsetup/setup/template/stepInstallPackages.tpl
Labels: Feature

#4402 Deprecate `WCF.Search.Message.KeywordList`
  wcfsetup/install/files/js/WCF.Search.Message.js
Labels: Bug

#4403 Add missing SQL log entry for `wcf1_acp_session_virtual` during upgrade to 5.4
  com.woltlab.wcf/files_pre_check.tar
  com.woltlab.wcf/package.xml
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4_fixSqlLog.php
Labels: Bug

#4405 Skip authenticators of deleted users in update_com.woltlab.wcf_5.4_migrate_multifactor.php
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4_migrate_multifactor.php
Labels: Bug

#4408 Add update_com.woltlab.wcf_5.4.2_deleteInvalidSessions.php
  com.woltlab.wcf/package.xml
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4.2_deleteInvalidSessions.php
Labels: Bug

#4411 Fall-back to GD if ImageMagick does not satisfy the requirements
  wcfsetup/install/files/lib/system/WCFSetup.class.php
  wcfsetup/test.php
Labels: Bug

#4412 Improve resiliency of the style cover photo upgrade script
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4_styleCoverPhoto.php
Labels: Feature

#4415 Help TSC understand the data flow in Dropdown/Simple#toggle
  ts/WoltLabSuite/Core/Ui/Dropdown/Simple.ts
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Dropdown/Simple.js
Labels: Bug

#4417 Delete the captcha registration after retrieving data in Comment/Add and Message/Reply
  ts/WoltLabSuite/Core/Ui/Comment/Add.ts
  ts/WoltLabSuite/Core/Ui/Message/Reply.ts
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Comment/Add.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Message/Reply.js
Labels: Bug

#4420 Add notice letting the user know quitting their account is active
  com.woltlab.wcf/templates/accountManagement.tpl
  com.woltlab.wcf/templates/userNotice.tpl
  wcfsetup/install/files/lib/form/AccountManagementForm.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#4422 Refer to RebuildDataPage in the system check for search engine tables
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Bug

#4421 Add files/acp/update_com.woltlab.wcf_5.4.3_deleteDsStore.php
  com.woltlab.wcf/package.xml
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4.3_deleteDsStore.php
Labels: Bug

#4423 Add PKCE support to AbstractOauth2Action
  wcfsetup/install/files/lib/action/AbstractOauth2Action.class.php
Labels: Feature

#4426 Properly show the label form field's selection if it has a value upon load
  com.woltlab.wcf/templates/__labelFormField.tpl
  wcfsetup/install/files/acp/templates/__labelFormField.tpl
Labels: Bug

#4427 Add missing check for dependencies in LabelFormField processor
  wcfsetup/install/files/lib/system/form/builder/field/label/LabelFormField.class.php
Labels: Bug
