Repository WoltLab/WCF, pull requests merged in 2021-01, with the labels that each got.

#3846 Convert a large amount of missing modules to TypeScript
  global.d.ts
  package-lock.json
  package.json
  wcfsetup/install/files/js/WCF.Assets.js
  wcfsetup/install/files/js/WCF.User.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Bootstrap.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/CodeMirror/Page.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Devtools/Notification/Test.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Devtools/Project/Installation/Confirmation.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Devtools/Project/Pip/Entry/List.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Devtools/Project/QuickSetup.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Devtools/Project/Sync.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Bbcode/Collapsible.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Bbcode/Spoiler.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Bootstrap.js
  wcfsetup/install/files/js/WoltLabSuite/Core/BootstrapFrontend.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Controller/Condition/Page/Dependence.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Controller/Map/Route/Planner.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Controller/Notice/Dismiss.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Controller/Popover.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Controller/Style/Changer.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Controller/User/Notification/Settings.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Bootstrap.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Bootstrap.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/CodeMirror/Page.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/CodeMirror/Page.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Devtools/Notification/Test.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Devtools/Notification/Test.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Devtools/Project/Installation/Confirmation.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Devtools/Project/Installation/Confirmation.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Devtools/Project/Pip/Entry/List.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Devtools/Project/Pip/Entry/List.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Devtools/Project/QuickSetup.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Devtools/Project/QuickSetup.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Devtools/Project/Sync.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Ui/Devtools/Project/Sync.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ajax/Data.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ajax/Request.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Bbcode/Collapsible.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Bbcode/Collapsible.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Bbcode/Spoiler.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Bbcode/Spoiler.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Bootstrap.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Bootstrap.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/BootstrapFrontend.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/BootstrapFrontend.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Condition/Page/Dependence.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Condition/Page/Dependence.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Map/Route/Planner.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Map/Route/Planner.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Notice/Dismiss.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Notice/Dismiss.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Popover.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Popover.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Style/Changer.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Style/Changer.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/User/Notification/Settings.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/User/Notification/Settings.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Confirmation.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Screen.ts
Labels: Feature

#3852 Stop filling in the user's profile on social registration
  wcfsetup/install/files/lib/action/FacebookAuthAction.class.php
  wcfsetup/install/files/lib/form/RegisterForm.class.php
Labels: Feature

#3853 Refactor OAuth 2 login
  com.woltlab.wcf/templates/accountManagement.tpl
  wcfsetup/install/files/lib/action/AbstractOauth2Action.class.php
  wcfsetup/install/files/lib/action/FacebookAuthAction.class.php
  wcfsetup/install/files/lib/action/GithubAuthAction.class.php
  wcfsetup/install/files/lib/action/GoogleAuthAction.class.php
  wcfsetup/install/files/lib/action/TwitterAuthAction.class.php
  wcfsetup/install/files/lib/form/AccountManagementForm.class.php
  wcfsetup/install/files/lib/form/RegisterForm.class.php
  wcfsetup/install/files/lib/system/user/authentication/oauth/User.class.php
  wcfsetup/install/files/lib/system/user/authentication/oauth/exception/StateValidationException.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#3867 Fail SMTP auth if credentials are configured but all mechanisms fail
  wcfsetup/install/files/lib/system/email/transport/SmtpEmailTransport.class.php
Labels: Bug

#3849 Convert media-related JavaScript to TypeScript
  wcfsetup/install/files/js/WoltLabSuite/Core/Controller/Media/List.js
  wcfsetup/install/files/js/WoltLabSuite/Core/FileUtil.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Media/Clipboard.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Media/Data.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Media/Editor.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Media/List/Upload.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Media/Manager/Base.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Media/Manager/Editor.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Media/Manager/Search.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Media/Manager/Select.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Media/Replace.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Media/Upload.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Upload.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Clipboard.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Media/List.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Controller/Media/List.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/FileUtil.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Clipboard.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Clipboard.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Data.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Editor.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Editor.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/List/Upload.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/List/Upload.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Manager/Base.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Manager/Base.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Manager/Editor.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Manager/Editor.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Manager/Search.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Manager/Search.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Manager/Select.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Manager/Select.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Replace.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Replace.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Upload.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Media/Upload.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Redactor/Editor.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Upload.ts
Labels: Feature

#3861 Support for WebP images
  com.woltlab.wcf/userGroupOption.xml
  wcfsetup/install/files/acp/templates/systemCheck.tpl
  wcfsetup/install/files/js/3rdParty/redactor2/redactor.js
  wcfsetup/install/files/js/WCF.Attachment.js
  wcfsetup/install/files/js/WCF.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Upload.js
  wcfsetup/install/files/lib/acp/page/SystemCheckPage.class.php
  wcfsetup/install/files/lib/data/style/StyleEditor.class.php
  wcfsetup/install/files/lib/data/user/avatar/UserAvatarAction.class.php
  wcfsetup/install/files/lib/page/AttachmentPage.class.php
  wcfsetup/install/files/lib/page/MediaPage.class.php
  wcfsetup/install/files/lib/system/file/upload/UploadHandler.class.php
  wcfsetup/install/files/lib/system/image/adapter/GDImageAdapter.class.php
  wcfsetup/install/files/lib/system/upload/UserCoverPhotoUploadFileValidationStrategy.class.php
  wcfsetup/install/files/lib/util/FileUtil.class.php
  wcfsetup/install/files/lib/util/ImageUtil.class.php
  wcfsetup/install/files/ts/WoltLabSuite/Core/Upload.ts
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#3869 Image adapters now support saving to GIF/JPG/PNG/WebP
  wcfsetup/install/files/lib/system/image/adapter/GDImageAdapter.class.php
  wcfsetup/install/files/lib/system/image/adapter/IImageAdapter.class.php
  wcfsetup/install/files/lib/system/image/adapter/ImageAdapter.class.php
  wcfsetup/install/files/lib/system/image/adapter/ImagickImageAdapter.class.php
Labels: Feature

#3860 Convert `WCF.Message.Quote.Handler` to TypeScript
  wcfsetup/install/files/js/WCF.Message.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Dom/Util.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Message/Quote.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Dom/Util.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Ui/Message/Quote.ts
Labels: Feature

#3865 Fix the style preview images
  com.woltlab.wcf/package.xml
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.3.2_style.php
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.3.3_style.php
Labels: Bug

#3871 Convert devtools project JavaScript code to TypeScript
  wcfsetup/install/files/acp/templates/__devtoolsProjectRequiredPackagesFormField.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/AbstractPackageList.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/Data.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/ExcludedPackages.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/Instructions.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/OptionalPackages.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/RequiredPackages.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/AbstractPackageList.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/AbstractPackageList.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/Data.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/ExcludedPackages.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/ExcludedPackages.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/Instructions.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/Instructions.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/OptionalPackages.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/OptionalPackages.ts
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/RequiredPackages.js
  wcfsetup/install/files/ts/WoltLabSuite/Core/Acp/Form/Builder/Field/Devtools/Project/RequiredPackages.ts
Labels: Feature

#3686 Replace usage of deprecated JavaScript code with new modules
  wcfsetup/install/files/acp/js/WCF.ACP.js
  wcfsetup/install/files/acp/templates/sendMailUserBulkProcessing.tpl
  wcfsetup/install/files/acp/templates/sitemapList.tpl
  wcfsetup/install/files/acp/templates/userActivityPointOption.tpl
  wcfsetup/install/files/acp/templates/userMail.tpl
Labels: Feature

#3879 Deprecate `WCF.System.Dependency.Manager`
  wcfsetup/install/files/js/WCF.js
Labels: Feature

#3877 Replace usage of `WCF.System.PageNavigation` with `Ui/Page/JumpTo`
  com.woltlab.wcf/templates/headIncludeJavaScript.tpl
  ts/WoltLabSuite/Core/Bootstrap.ts
  wcfsetup/install/files/acp/templates/header.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Bootstrap.js
Labels: Feature

#3873 Fix performance of user online list
  wcfsetup/install/files/lib/data/user/online/UserOnline.class.php
  wcfsetup/install/files/lib/data/user/online/UsersOnlineList.class.php
Labels: Bug

#3884 Add support for phpBB's combined hash
  wcfsetup/install/files/lib/util/PasswordUtil.class.php
Labels: Bug

#3896 Add button to delete missing phrases logs for phrases existing now
  ts/WoltLabSuite/Core/Acp/Ui/Devtools/Missing/Language/Item/List.ts
  wcfsetup/install/files/acp/templates/devtoolsMissingLanguageItemList.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Devtools/Missing/Language/Item/List.js
  wcfsetup/install/files/lib/data/devtools/missing/language/item/DevtoolsMissingLanguageItemAction.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#3890 New UI design for the list of attachments
  com.woltlab.wcf/templates/attachments.tpl
  wcfsetup/install/files/style/ui/attachment.scss
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#3889 Dynamic WebP avatars
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4_db.php
  wcfsetup/install/files/lib/data/user/avatar/UserAvatar.class.php
  wcfsetup/install/files/lib/data/user/avatar/UserAvatarEditor.class.php
  wcfsetup/install/files/lib/system/upload/AvatarUploadFileSaveStrategy.class.php
  wcfsetup/install/files/lib/system/worker/UserRebuildDataWorker.class.php
  wcfsetup/install/files/lib/util/ImageUtil.class.php
  wcfsetup/setup/db/install.sql
Labels: Feature

#3903 Improved message for rejected credentials on paid packages
  wcfsetup/install/files/acp/templates/packageUpdateUnauthorizedPurchaseRequired.tpl
  wcfsetup/install/files/lib/system/package/PackageUpdateUnauthorizedException.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#3905 Replace placeholders by actual values in Benchmark
  wcfsetup/install/files/lib/system/database/statement/PreparedStatement.class.php
Labels: Feature

#3906 Use the `input` event to detect the comma on Chromium for Android
  ts/WoltLabSuite/Core/Ui/ItemList.ts
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/ItemList.js
Labels: Bug, P2: Low

#3917 WebP support for cover photos
  com.woltlab.wcf/option.xml
  com.woltlab.wcf/templates/user.tpl
  constants.php
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4_db.php
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4_styleCoverPhoto.php
  wcfsetup/install/files/images/coverPhotos/default.webp
  wcfsetup/install/files/lib/acp/form/StyleAddForm.class.php
  wcfsetup/install/files/lib/data/style/Style.class.php
  wcfsetup/install/files/lib/data/style/StyleAction.class.php
  wcfsetup/install/files/lib/data/style/StyleEditor.class.php
  wcfsetup/install/files/lib/data/user/User.class.php
  wcfsetup/install/files/lib/data/user/UserProfile.class.php
  wcfsetup/install/files/lib/data/user/UserProfileAction.class.php
  wcfsetup/install/files/lib/data/user/cover/photo/DefaultUserCoverPhoto.class.php
  wcfsetup/install/files/lib/data/user/cover/photo/IUserCoverPhoto.class.php
  wcfsetup/install/files/lib/data/user/cover/photo/UserCoverPhoto.class.php
  wcfsetup/install/files/lib/system/WCF.class.php
  wcfsetup/install/files/lib/system/upload/UserCoverPhotoUploadFileSaveStrategy.class.php
  wcfsetup/install/files/lib/util/ImageUtil.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
  wcfsetup/setup/db/install.sql
Labels: Feature
