Repository WoltLab/WCF, pull requests merged in 2021-08, with the labels that each got.

#4431 Fix `{foreach}` loops when the to-be-iterated value is empty
  wcfsetup/install/files/lib/system/template/TemplateScriptingCompiler.class.php
Labels: Bug

#4432 Do not store optional information from update servers within the database
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.5_clearPackageDeprecations.php
  wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php
  wcfsetup/setup/db/install.sql
Labels: Bug

#4429 Support ES 6 default exports for form builder field JavaScript data handlers
  com.woltlab.wcf/templates/__formFieldDataHandler.tpl
  wcfsetup/install/files/acp/templates/__formFieldDataHandler.tpl
Labels: Bug

#4430 Resolved side effects from previous inheritance approach
  ts/WoltLabSuite/Core/Core.ts
  wcfsetup/install/files/js/WoltLabSuite/Core/Core.js
Labels: Bug, P0: High

#4433 PHP DDL Fixes
  wcfsetup/install/files/lib/system/database/table/DatabaseTableChangeProcessor.class.php
Labels: Bug

#4435 PHP DDL Fixes
  wcfsetup/install/files/lib/system/database/table/DatabaseTableChangeProcessor.class.php
Labels: Bug

#4438 Fix having an incorrect parameter if a hash does not contains a salt
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Ipb2.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Ipb3.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Joomla1.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Joomla2.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Joomla3.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Mybb1.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Phpfox3.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Smf1.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Smf2.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Vb3.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Vb4.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Vb5.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Wcf1.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Wcf1e.class.php
  wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Xf1.class.php
Labels: Bug

#4439 Fixes Bings Sitemap Howto
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Bug

#4440 Add proxy_sourcemap.php
  wcfsetup/install/files/proxy_sourcemap.php
Labels: Bug

#4446 Show nicer error message if allocating the MFA setup fails
  wcfsetup/install/files/lib/form/MultifactorManageForm.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Bug

#4451 Fix conditions for MultiSelectOptionType
  wcfsetup/install/files/lib/system/option/MultiSelectOptionType.class.php
Labels: Bug

#4452 Deprecate MessageQuoteAction::markForRemoval()
  wcfsetup/install/files/js/WCF.Message.js
  wcfsetup/install/files/lib/action/MessageQuoteAction.class.php
Labels: Bug

#4453 Check whether an IFormButton is available before rendering
  com.woltlab.wcf/templates/__form.tpl
  wcfsetup/install/files/acp/templates/__form.tpl
Labels: Bug

#4454 Add `cache-control: private` to PSR-7 responses
  wcfsetup/install/files/lib/system/request/RequestHandler.class.php
Labels: Feature

#4456 Prevent StyleEditForm from creating phrases with empty name
  com.woltlab.wcf/package.xml
  wcfsetup/install/files/lib/acp/form/StyleEditForm.class.php
  wcfsetup/install/files/lib/data/language/LanguageEditor.class.php
  wcfsetup/install/files/lib/system/language/I18nHandler.class.php
Labels: Bug

#4450 Rename `Ui/Object/Action/Toogle` to `Toggle`
  ts/WoltLabSuite/Core/Bootstrap.ts
  ts/WoltLabSuite/Core/Ui/Object/Action/Toggle.ts
  ts/WoltLabSuite/Core/Ui/Object/Action/Toogle.ts
  wcfsetup/install/files/js/WoltLabSuite/Core/Bootstrap.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Object/Action/Toggle.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/Object/Action/Toogle.js
Labels: Bug

#4461 Move PHP 7.3 from recommended to sufficient in SystemCheckPage
  wcfsetup/install/files/lib/acp/page/SystemCheckPage.class.php
Labels: Feature

#4462 Add Message-ID filter to email log
  wcfsetup/install/files/acp/templates/emailLogList.tpl
  wcfsetup/install/files/lib/acp/page/EmailLogListPage.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#4463 Fix Unicode in smiley titles
  wcfsetup/install/files/lib/system/html/output/node/HtmlOutputNodeImg.class.php
Labels: Bug

#4464 Fix unpacking of the sessionId
  wcfsetup/install/files/lib/system/session/SessionHandler.class.php
Labels: Bug

#4349 Add User Edit dropdown on UserEditPage
  ts/WoltLabSuite/Core/Acp/Ui/User/Action/Abstract.ts
  ts/WoltLabSuite/Core/Acp/Ui/User/Action/BanAction.ts
  ts/WoltLabSuite/Core/Acp/Ui/User/Action/DeleteAction.ts
  ts/WoltLabSuite/Core/Acp/Ui/User/Action/DisableAction.ts
  ts/WoltLabSuite/Core/Acp/Ui/User/Action/Handler/Ban.ts
  ts/WoltLabSuite/Core/Acp/Ui/User/Action/Handler/Ban/Dialog.ts
  ts/WoltLabSuite/Core/Acp/Ui/User/Action/Handler/Delete.ts
  ts/WoltLabSuite/Core/Acp/Ui/User/Action/Handler/SendNewPassword.ts
  ts/WoltLabSuite/Core/Acp/Ui/User/Action/SendNewPasswordAction.ts
  ts/WoltLabSuite/Core/Acp/Ui/User/Action/ToggleConfirmEmailAction.ts
  ts/WoltLabSuite/Core/Acp/Ui/User/Content/Remove/Handler.ts
  ts/WoltLabSuite/Core/Acp/Ui/User/Editor.ts
  wcfsetup/install/files/acp/templates/userAdd.tpl
  wcfsetup/install/files/acp/templates/userList.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Action/Abstract.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Action/AbstractUserAction.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Action/BanAction.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Action/DeleteAction.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Action/DisableAction.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Action/Handler/Ban.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Action/Handler/Ban/Dialog.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Action/Handler/Delete.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Action/Handler/SendNewPassword.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Action/SendNewPasswordAction.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Action/ToggleConfirmEmailAction.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Content/Remove/Handler.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/User/Editor.js
Labels: Feature

#4465 Use PSR-7 responses in `TwitterAuthAction`
  wcfsetup/install/files/lib/action/TwitterAuthAction.class.php
Labels: Feature

#4467 Fix handling of cover photos in UserRebuildDataWorker
  wcfsetup/install/files/lib/system/worker/UserRebuildDataWorker.class.php
Labels: Bug

#4470 Ensure that the OAuth 2 state parameter is cleared in all cases
  wcfsetup/install/files/lib/action/AbstractOauth2Action.class.php
Labels: Bug
