Repository WoltLab/WCF, pull requests merged in 2022-05, with the labels that each got.

#4766 fix application management in multi domain setups
  wcfsetup/install/files/lib/acp/form/ApplicationManagementForm.class.php
Labels: Bug

#4768 Fix handling of CMS pages in sitemap
  wcfsetup/install/files/lib/system/sitemap/object/MultilingualPageSitemapObject.class.php
  wcfsetup/install/files/lib/system/sitemap/object/SimplePageSitemapObject.class.php
Labels: Bug

#4781 Flip only the file name casing on AbstractFileDeletePackageInstallationPlugin::isFilesystemCaseSensitive()
  wcfsetup/install/files/lib/system/package/plugin/AbstractFileDeletePackageInstallationPlugin.class.php
Labels: Bug

#4784 Require 64-bit support
  wcfsetup/install/files/acp/templates/systemCheck.tpl
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.5_checkSystemRequirements.php
  wcfsetup/install/files/lib/acp/page/SystemCheckPage.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
  wcfsetup/setup/lang/setup_de.xml
  wcfsetup/setup/lang/setup_en.xml
  wcfsetup/setup/template/stepShowSystemRequirements.tpl
Labels: Feature

#4791 Remove the WCF_N input in WCFSetup
  extra/examples/wsc-dev-config-55.json
  wcfsetup/install/files/lib/system/WCFSetup.class.php
  wcfsetup/install/files/lib/system/devtools/DevtoolsSetup.class.php
  wcfsetup/setup/lang/setup_de.xml
  wcfsetup/setup/lang/setup_en.xml
  wcfsetup/setup/template/stepConfigureDB.tpl
Labels: Feature

#4797 Increase minimum MySQL version to 8.0.29 / MariaDB 10.5.12
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.5_checkSystemRequirements.php
  wcfsetup/install/files/lib/acp/form/PackageEnableUpgradeOverrideForm.class.php
  wcfsetup/install/files/lib/acp/page/SystemCheckPage.class.php
  wcfsetup/install/files/lib/system/WCFSetup.class.php
  wcfsetup/test.php
Labels: Feature

#4788 Always restrict valid template modifiers to an allow list
  wcfsetup/install/files/lib/system/template/TemplateScriptingCompiler.class.php
Labels: Feature

#4796 Remove the obsolete stripping of the `s=<sessionID>` when handling the canonical URL
  wcfsetup/install/files/lib/page/AbstractPage.class.php
Labels: Bug

#4794 Remove obsolete WCFACP::initPackage()
  wcfsetup/install/files/lib/system/WCFACP.class.php
Labels: Bug

#4793 Use HTTP 500 in error conditions
  wcfsetup/install/files/lib/system/WCF.class.php
  wcfsetup/install/files/proxy_sourcemap.php
Labels: Feature

#4795 Remove unneeded usage of `mb_strpos`
  wcfsetup/install/files/lib/acp/form/UserGroupAddForm.class.php
  wcfsetup/install/files/lib/acp/page/ExceptionLogViewPage.class.php
  wcfsetup/install/files/lib/data/option/Option.class.php
  wcfsetup/install/files/lib/data/package/Package.class.php
  wcfsetup/install/files/lib/page/AbstractPage.class.php
  wcfsetup/install/files/lib/page/MembersListPage.class.php
  wcfsetup/install/files/lib/system/WCFSetup.class.php
  wcfsetup/install/files/lib/system/bbcode/SimpleMessageParser.class.php
  wcfsetup/install/files/lib/system/bbcode/highlighter/PhpHighlighter.class.php
  wcfsetup/install/files/lib/system/condition/UserEmailCondition.class.php
  wcfsetup/install/files/lib/system/condition/UserUsernameCondition.class.php
  wcfsetup/install/files/lib/system/exception/ValidateActionException.class.php
  wcfsetup/install/files/lib/system/form/FormDocument.class.php
  wcfsetup/install/files/lib/system/html/input/node/HtmlInputNodeTextParser.class.php
  wcfsetup/install/files/lib/system/html/metacode/converter/CodeMetacodeConverter.class.php
  wcfsetup/install/files/lib/system/html/metacode/converter/ListMetacodeConverter.class.php
  wcfsetup/install/files/lib/system/html/metacode/converter/UrlMetacodeConverter.class.php
  wcfsetup/install/files/lib/system/html/node/AbstractHtmlNodeProcessor.class.php
  wcfsetup/install/files/lib/system/html/output/node/HtmlOutputNodePre.class.php
  wcfsetup/install/files/lib/system/html/output/node/HtmlOutputNodeWoltlabQuote.class.php
  wcfsetup/install/files/lib/system/message/censorship/Censorship.class.php
  wcfsetup/install/files/lib/system/option/RadioButtonOptionType.class.php
  wcfsetup/install/files/lib/system/option/user/SelectOptionsUserOptionOutput.class.php
  wcfsetup/install/files/lib/system/setup/Installer.class.php
  wcfsetup/install/files/lib/system/template/TemplateScriptingCompiler.class.php
  wcfsetup/install/files/lib/util/CronjobUtil.class.php
  wcfsetup/install/files/lib/util/HeaderUtil.class.php
  wcfsetup/install/files/lib/util/OptionUtil.class.php
  wcfsetup/install/files/lib/util/StringStack.class.php
  wcfsetup/install/files/lib/util/StringUtil.class.php
  wcfsetup/install/files/lib/util/Url.class.php
Labels: Bug

#4799 Immediately destroy the session for banned users
  wcfsetup/install/files/lib/system/WCF.class.php
Labels: Feature

#4790 Enforce TLS for package servers
  wcfsetup/install/files/acp/templates/index.tpl
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.5_checkUpdateServers.php
  wcfsetup/install/files/lib/acp/form/PackageUpdateServerAddForm.class.php
  wcfsetup/install/files/lib/acp/page/IndexPage.class.php
  wcfsetup/install/files/lib/data/package/PackageAction.class.php
  wcfsetup/install/files/lib/data/package/update/server/PackageUpdateServer.class.php
  wcfsetup/install/files/lib/system/io/RemoteFile.class.php
  wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
  wcfsetup/setup/db/install.sql
Labels: Feature

#4802 Use PHP 8.2's SensitiveParameter argument
  wcfsetup/install.php
  wcfsetup/install/files/lib/core.functions.php
  wcfsetup/install/files/lib/data/user/User.class.php
  wcfsetup/install/files/lib/system/user/authentication/DefaultUserAuthentication.class.php
Labels: Feature

#4800 Deprecate StringUtil::convertEncoding()
  wcfsetup/install/files/lib/action/PaypalCallbackAction.class.php
  wcfsetup/install/files/lib/page/AbstractPage.class.php
  wcfsetup/install/files/lib/system/bbcode/KeywordHighlighter.class.php
  wcfsetup/install/files/lib/system/message/unfurl/UnfurlResponse.class.php
  wcfsetup/install/files/lib/util/StringUtil.class.php
  wcfsetup/install/files/lib/util/UserUtil.class.php
Labels: Feature

#4801 Remove long-deprecated JavaScript template events from `headInclude.tpl`
  com.woltlab.wcf/templates/headInclude.tpl
  com.woltlab.wcf/templates/headIncludeJavaScript.tpl
Labels: Bug

#4808 HTTP 204 does not carry a response type
  ts/WoltLabSuite/Core/Acp/Ui/DataImport/Manager.ts
  ts/WoltLabSuite/Core/Ajax/Request.ts
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/DataImport/Manager.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ajax/Request.js
Labels: Bug, P0: High

#4810 Remove dynamic dispatch of common cases from GZipFile
  wcfsetup/install.php
  wcfsetup/install/files/lib/system/io/GZipFile.class.php
Labels: Feature

#4811 Clean up finalization of WCFSetup
  wcfsetup/install/files/lib/system/WCFSetup.class.php
Labels: Bug

#4814 Clean up the handling of temporary files during WCFSetup
  wcfsetup/install.php
  wcfsetup/install/files/lib/system/WCFSetup.class.php
Labels: Feature

#4815 Remove the need for SetupTemplateCompiler
  wcfsetup/install/files/lib/system/WCFSetup.class.php
  wcfsetup/install/files/lib/system/template/SetupTemplateCompiler.class.php
  wcfsetup/install/files/lib/system/template/SetupTemplateEngine.class.php
  wcfsetup/setup/template/stepInstallPackages.tpl
Labels: Bug

#4818 Migrate WCFSetup to PSR-7
  wcfsetup/install/files/lib/system/WCFSetup.class.php
  wcfsetup/setup/template/stepShowLicense.tpl
Labels: Feature

#4821 Clean all directories that match the tmp naming pattern at the end of WCFSetup
  wcfsetup/install.php
  wcfsetup/install/files/lib/system/WCFSetup.class.php
Labels: Bug

#4825 Moved the notification list into the global space
  com.woltlab.wcf/page.xml
  com.woltlab.wcf/templates/notificationList.tpl
  com.woltlab.wcf/userMenu.xml
  wcfsetup/install/files/lib/page/NotificationListPage.class.php
Labels: Feature

#4822 Clean up route processing in RequestHandler
  wcfsetup/install/files/lib/system/request/ControllerMap.class.php
  wcfsetup/install/files/lib/system/request/Request.class.php
  wcfsetup/install/files/lib/system/request/RequestHandler.class.php
  wcfsetup/install/files/lib/system/request/RouteHandler.class.php
Labels: Feature

#4826 Remove obsolete upgrade workarounds
  wcfsetup/install/files/lib/system/application/ApplicationHandler.class.php
  wcfsetup/install/files/lib/system/cache/builder/RoutingCacheBuilder.class.php
Labels: Bug

#4827 Move the `WSC_API_URL` into com.woltlab.wcf
  com.woltlab.wcf/templates/headIncludeJavaScript.tpl
  wcfsetup/install/files/acp/templates/header.tpl
  wcfsetup/install/files/lib/system/WCF.class.php
  wcfsetup/install/files/lib/system/request/ControllerMap.class.php
Labels: Feature

#4828 Remove enforced redirect of `login` and `index` controller in ACP to the `wcf` application
  wcfsetup/install/files/lib/system/request/LinkHandler.class.php
  wcfsetup/install/files/lib/system/request/RequestHandler.class.php
Labels: Feature

#4829 Remove upgrade workarounds for default controller of `wcf`
  wcfsetup/install/files/lib/system/cache/builder/RoutingCacheBuilder.class.php
  wcfsetup/install/files/lib/system/request/ControllerMap.class.php
  wcfsetup/install/files/lib/system/request/RequestHandler.class.php
Labels: Bug

#4830 Remove magic numbers from RoutingCacheBuilder's landingPages data
  wcfsetup/install/files/lib/system/cache/builder/RoutingCacheBuilder.class.php
  wcfsetup/install/files/lib/system/request/ControllerMap.class.php
Labels: Feature

#4832 Remove RouteHandler::getDefaultController()
  wcfsetup/install/files/lib/system/request/RouteHandler.class.php
Labels: Bug

#4839 Deprecate SessionHandler::getLanguageIDs()
  wcfsetup/install/files/lib/system/session/SessionHandler.class.php
Labels: Bug
