Repository WoltLab/WCF, pull requests merged in 2022-07, with the labels that each got.

#4886 Update the Unread Counter Using the Server-side Counter
  ts/WoltLabSuite/Core/Ui/User/Menu/Data/ModerationQueue.ts
  ts/WoltLabSuite/Core/Ui/User/Menu/Data/Notification.ts
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/User/Menu/Data/ModerationQueue.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/User/Menu/Data/Notification.js
  wcfsetup/install/files/lib/data/moderation/queue/ModerationQueueAction.class.php
  wcfsetup/install/files/lib/data/user/notification/UserNotificationAction.class.php
Labels: Bug, P1: Medium

#4890 Always allow disabling the upgrade override if enabled
  wcfsetup/install/files/lib/acp/form/PackageEnableUpgradeOverrideForm.class.php
Labels: Bug

#4892 Remove the FetchCompilerTemplatePlugin
  com.woltlab.wcf/fileDelete.xml
  wcfsetup/install/files/lib/system/template/plugin/FetchCompilerTemplatePlugin.class.php
Labels: Bug

#4893 Select the first erroneous tab in a form if multiple are erroneous
  ts/WoltLabSuite/Core/Ui/TabMenu.ts
  tsconfig.json
  wcfsetup/install/files/js/WoltLabSuite/Core/Ui/TabMenu.js
Labels: Bug

#4894 Make AbstractCategoryEditForm actually abstract
  wcfsetup/install/files/lib/acp/form/AbstractCategoryAddForm.class.php
  wcfsetup/install/files/lib/acp/form/AbstractCategoryEditForm.class.php
Labels: Bug

#4895 Make AbstractAjaxAction actually abstract
  wcfsetup/install/files/lib/action/AbstractAjaxAction.class.php
Labels: Bug

#4896 Verify that the category's objectType matches the form's objectType in AbstractCategoryEditForm
  wcfsetup/install/files/lib/acp/form/AbstractCategoryEditForm.class.php
Labels: Bug

#4897 Explicitly handle a `null` value in UserOptionOutput
  wcfsetup/install/files/lib/system/option/user/MessageUserOptionOutput.class.php
  wcfsetup/install/files/lib/system/option/user/NewlineToBreakUserOptionOutput.class.php
  wcfsetup/install/files/lib/system/option/user/SelectOptionsUserOptionOutput.class.php
Labels: Bug

#4898 Rerun the .DS_Store deletion script
  com.woltlab.wcf/package.xml
  wcfsetup/install/files/acp/update_com.woltlab.wcf_5.5_deleteDsStore.php
Labels: Bug

#4908 Add explicit “success” message to PackageEnableUpgradeOverrideForm
  wcfsetup/install/files/acp/templates/packageEnableUpgradeOverrideSuccess.tpl
  wcfsetup/install/files/lib/acp/form/PackageEnableUpgradeOverrideForm.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#4914 Store SHA-256 hashes in `wcf1_package_installation_file_log`
  wcfsetup/install/files/acp/database/update_com.woltlab.wcf_5.6.php
  wcfsetup/install/files/lib/system/package/FilesFileHandler.class.php
  wcfsetup/install/files/lib/system/package/plugin/FilePackageInstallationPlugin.class.php
  wcfsetup/setup/db/install.sql
Labels: Feature
