Repository WoltLab/WCF, pull requests merged in 2023-08, with the labels that each got.

#5597 Require a `_fk` suffix for explicit FOREIGN KEY names
  wcfsetup/install/files/lib/system/database/table/DatabaseTableChangeProcessor.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Bug

#5599 Augment the EditorConfig with `woltlabBbcode` in Ckeditor/Types
  ts/WoltLabSuite/Core/Component/Ckeditor/Types.ts
Labels: Feature

#5598 Enable the image resizing in CKEditor again
  com.woltlab.wcf/bbcode.xml
  wcfsetup/install/files/js/3rdParty/ckeditor/ckeditor5.bundle.js
  wcfsetup/install/files/lib/system/bbcode/AttachmentBBCode.class.php
  wcfsetup/install/files/lib/system/html/input/filter/MessageHtmlInputFilter.class.php
  wcfsetup/install/files/lib/system/html/input/node/HtmlInputNodeImg.class.php
Labels: Feature

#5601 Accept `float`s in FileUtil::checkMemoryLimit()
  wcfsetup/install/files/lib/util/FileUtil.class.php
Labels: Feature

#5602 Make use of `ini_parse_quantity()` in FileUtil::getMemoryLimit()
  wcfsetup/install/files/lib/util/FileUtil.class.php
Labels: Feature

#5603 Use `FileUtil::getMemoryLimit()` in SystemCheckPage
  wcfsetup/install/files/lib/acp/page/SystemCheckPage.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Bug

#5608 Update Spotify media provider
  com.woltlab.wcf/mediaProvider.xml
Labels: Feature

#5616 Overhaul the color scheme selection
  com.woltlab.wcf/templates/headIncludeJavaScript.tpl
  com.woltlab.wcf/templates/pageFooter.tpl
  com.woltlab.wcf/templates/settings.tpl
  com.woltlab.wcf/userOption.xml
  ts/WoltLabSuite/Core/Acp/Bootstrap.ts
  ts/WoltLabSuite/Core/Bootstrap.ts
  ts/WoltLabSuite/Core/BootstrapFrontend.ts
  ts/WoltLabSuite/Core/Controller/Style/ColorScheme.ts
  wcfsetup/install/files/acp/templates/header.tpl
  wcfsetup/install/files/acp/templates/pageHeaderUser.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Bootstrap.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Bootstrap.js
  wcfsetup/install/files/js/WoltLabSuite/Core/BootstrapFrontend.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Controller/Style/ColorScheme.js
  wcfsetup/install/files/lib/form/SettingsForm.class.php
  wcfsetup/install/files/lib/system/event/listener/PreloadPhrasesCollectingListener.class.php
  wcfsetup/install/files/lib/system/style/StyleHandler.class.php
  wcfsetup/install/files/lib/system/user/command/SetColorScheme.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Feature

#5618 Add `[data-formbuilder]` and `Psr15DialogFormResponse`
  ts/WoltLabSuite/Core/Bootstrap.ts
  ts/WoltLabSuite/Core/Component/FormBuilder/Button.ts
  wcfsetup/install/files/js/WoltLabSuite/Core/Bootstrap.js
  wcfsetup/install/files/js/WoltLabSuite/Core/Component/FormBuilder/Button.js
  wcfsetup/install/files/lib/system/form/builder/Psr15DialogFormResponse.class.php
Labels: Feature

#5621 fix usage of forbidden functions in templates
  com.woltlab.wcf/templates/aclPermissionJavaScript.tpl
  com.woltlab.wcf/templates/email_dailyNotification.tpl
  wcfsetup/install/files/acp/templates/aclPermissionJavaScript.tpl
  wcfsetup/install/files/lib/system/cronjob/DailyMailNotificationCronjob.class.php
  wcfsetup/install/files/lib/system/cronjob/ExceptionMailerCronjob.class.php
  wcfsetup/install/files/lib/system/package/plugin/BBCodePackageInstallationPlugin.class.php
  wcfsetup/install/files/lib/system/package/plugin/SmileyPackageInstallationPlugin.class.php
  wcfsetup/install/lang/de.xml
  wcfsetup/install/lang/en.xml
Labels: Bug

#5615 Insert trim to remove empty values
  wcfsetup/install/files/lib/system/form/builder/field/ItemListFormField.class.php
Labels: Needs Triage

#5628 Minify WebComponent.js when building with esbuild
  .github/workflows/typescript.yml
  package.json
  wcfsetup/install/files/js/WoltLabSuite/WebComponent.js
Labels: Feature

#5629 Prevent attempts to generate thumbnails for underflowing images
  wcfsetup/install/files/lib/system/upload/DefaultUploadFileSaveStrategy.class.php
Labels: Bug

#5631 Fix the test for the correct set-up of index.php-less URLs
  ts/WoltLabSuite/Core/Acp/Ui/Option/RewriteTest.ts
  wcfsetup/install/files/acp/templates/__optionRewriteTest.tpl
  wcfsetup/install/files/js/WoltLabSuite/Core/Acp/Ui/Option/RewriteTest.js
  wcfsetup/install/files/lib/acp/form/OptionForm.class.php
  wcfsetup/install/files/lib/action/CoreRewriteTestAction.class.php
  wcfsetup/install/files/lib/system/request/ControllerMap.class.php
Labels: Bug

#5634 Suppress stack frames from the middleware
  wcfsetup/install/files/lib/core.functions.php
Labels: Feature
